import { Button, Input, InputLabel } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

function strip(phone: string): string {
  let p = phone;
  p = p.replaceAll("-", "");
  p = p.replaceAll(".", "");
  p = p.replaceAll("(", "");
  p = p.replaceAll(")", "");
  p = p.replaceAll(" ", "");
  return p;
}

const Home: NextPage = () => {
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");

  const phoneRegex =
    /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/im;
  const spaceRegex = /\s\s+/g;

  function submit() {
    if (name.replace(spaceRegex, "").length == 0) {
      alert("Empty name");
      return;
    }
    if (!phoneRegex.test(phone)) {
      alert("Invalid phone number");
      return;
    }

    setPhone(strip(phone));

    fetch("/api/amonga", {
      method: "POST",
      body: JSON.stringify({ name: name, phone: phone }),
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Ballin&apos; Drones Inc.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Ballin&apos; Drones Inc.</h1>
        <h2>Our Mission</h2>
        <p style={{ width: "50%", textAlign: "center" }}>
          Our mission to create a better viewing experience for tennis viewer
          all around the world. Our technology will allow a never before seen
          level of immersion of the game.
        </p>
        <h3>Contact Us</h3>
        <div
          style={{ padding: "2.5%", marginLeft: "auto", marginRight: "auto" }}
        >
          <InputLabel>Your Name</InputLabel>
          <Input
            placeholder="Your name"
            defaultValue=""
            onChange={(e) => setName(e.target.value)}
          />
          <InputLabel>Phone Number</InputLabel>
          <Input
            placeholder="Your phone number"
            defaultValue=""
            onChange={(e) => setPhone(e.target.value)}
          />
          <br />
          <Button color="primary" variant="contained" onClick={submit}>
            Submit
          </Button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Manscaped Lawnmower 4.0
        </a>
      </footer>
    </div>
  );
};

export default Home;
